export enum ActionTypes {
  GET_COUNTRIES_START = 'countries/GET_COUNTRIES_START',
  GET_COUNTRIES_END = 'countries/GET_COUNTRIES_END',
  GET_COUNTRIES_SUCCESS = 'countries/GET_COUNTRIES_SUCCESS',
  GET_COUNTRIES_FAIL = 'countries/GET_COUNTRIES_FAIL'
}
