name: Test PR

on:
  push:
    branches:
      - '**'

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-18.04
    timeout-minutes: 15

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Node v14
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          check-latest: true

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            public
          key: cache-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            staging-cache
            cache-node

      - name: Install Packages
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        uses: sergioramos/yarn-actions/install@v6
        with:
          frozen-lockfile: true

      - name: Run Jest Tests
        run: yarn run test:c

      - name: Jest Badges
        run: yarn run test:badges
